### ISSUE TITLE
Trying to run Smappee-client but fail

### ISSUE THREAD

**Issue by vandura231** [NMichas/smappee-local-mqtt#2]
Are you still maintaining this component ?  If not.. don't bother, I'll try and find another way.
I'm having trouble with the setup of the smappee component.
when applying - 

sudo systemctl start smappee-client

and checking status I get an error:

 smappee-client.service - Smappee client Daemon
   Loaded: loaded (/lib/systemd/system/smappee-client.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2018-11-24 01:00:16 CET; 16h ago
  Process: 1165 ExecStart=/usr/bin/java -jar smappee-local-mqtt-1.0.0.jar (code=exited, status=203/EXEC)
 Main PID: 1165 (code=exited, status=203/EXEC)

Nov 24 01:00:16 Hassbian systemd[1]: Started Smappee client Daemon.
Nov 24 01:00:16 Hassbian systemd[1]: smappee-client.service: Main process exited, code=exited, status=203/EXEC
Nov 24 01:00:16 Hassbian systemd[1]: smappee-client.service: Unit entered failed state.
Nov 24 01:00:16 Hassbian systemd[1]: smappee-client.service: Failed with result 'exit-code'.

Any tips ? Don't know where to start :-s

Thx!

**Comment by NMichas** [comment]
I've switched to OpenHAB, so not using this anymore. Does it work for you when you try it from cli/non-service mode? e.g. `java -jar smappee-local-mqtt-1.0.0.jar`? If it does, then there should be something wrong with your service definition, you could debug that with `journalctl` and check for relevant logs.

**Comment by vandura231** [comment]
Thx for you response, No, it doesn't work. 
" -bash: java: command not found "  is the response I get.  Thx for tryin' to help me out but this is a llitlle too much for me :-)
I'm gonna leave the smappee out of my configuration, too much hassle…  
Kind Regards
JH

**Comment by vandura231** [comment]
I think I got it running, Did  some google, 
- installed java, and the client seems to be running with no errors :-)

Thx!

**Comment by NMichas** [comment]
Nice ;)
